import Head from "next/head";
import {  getSession } from "next-auth/react";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Homepage from "../components/Homepage";
const inter = Inter({ subsets: ["latin"] });

export default function Home(session) {
  console.log(session);
 
  return (
    <>
      <Head>
        <title>Movibies</title>
        <meta name="description" content="Generated by Romeoscript" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Homepage />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {

    return {
      redirect: {
        destination: "/Login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}
